name: Website Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy_website]') || contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Configure Git Credientials
        run: |
          git config --global user.email "theguild-bot@users.noreply.github.com"
          git config --global user.name "theguild-bot"
          echo "machine github.com login theguild-bot password ${{secrets.GITHUB_TOKEN}}" > ~/.netrc
      - name: Add origin remote and refetch master
        run: |
          git remote rm origin
          git remote add origin "https://github.com/${{github.repository}}"
          git fetch
          git checkout master
          git reset --hard
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: install pnpm
        run: npm i pnpm@^6.7.1 -g
      - name: Install Dependencies
        run: pnpm i
      - name: Deploy 🚀
        run: pnpm deploy:website
        env:
          GIT_USER: theguild-bot
